# Generated by Django 3.2.5 on 2023-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_emailverifications_phoneverifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(default=True),
        ),
    ]
