# Generated by Django 3.2.5 on 2023-04-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='offer_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
