# Generated by Django 3.2.5 on 2023-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_packages_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='color',
            field=models.CharField(default='green', max_length=50),
        ),
    ]
