# Generated by Django 3.2.5 on 2023-05-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230517_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
    ]
