# Generated by Django 3.2.5 on 2023-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transactions_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='invoice',
            field=models.FileField(upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
