# Generated by Django 3.2.5 on 2023-05-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='product_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
