# Generated by Django 3.2.5 on 2023-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_updates_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='execution',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'positive'), ('NEGATIVE', 'negative')], max_length=50, null=True),
        ),
    ]
