# Generated by Django 3.2.5 on 2023-05-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230518_1747'),
        ('research', '0003_updates_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls', models.TextField()),
                ('updates', models.TextField(blank=True, null=True)),
                ('stock_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_sell', models.CharField(blank=True, max_length=50, null=True)),
                ('call_put', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('strike_price', models.CharField(blank=True, max_length=50, null=True)),
                ('ct', models.CharField(blank=True, max_length=50, null=True)),
                ('stockPrice', models.CharField(blank=True, max_length=20, null=True)),
                ('lotsize', models.CharField(blank=True, max_length=20, null=True)),
                ('profit_loss', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('segmant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
