# Generated by Django 3.2.5 on 2023-05-25 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0004_callshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='callshistory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserBaseCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callType', models.CharField(choices=[('C', 'call'), ('U', 'update')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.callshistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
