# Generated by Django 3.2.5 on 2023-05-26 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0005_auto_20230525_1537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbasecall',
            unique_together={('user', 'call', 'callType')},
        ),
    ]
